# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish PBT to PyPI

on:
  push:
    tags:
      - 1.*
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install ".[test]"
        pip install build
    - name: Lint with Black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black --check src/ test/

    - name: Test with pytest
      run: |
        ##### TODO it looks like ivy2 cache is being clobbered by concurrent processes:
        #### https://lists.apache.org/thread/4xp1cgtzd99ntvwtv0lbdc25no0ctq79
        #### yeah.... ivy has a lockstrategy that is not usually set. 
        ### so we can either change defaultCacheDir or lockStrategy in ivysettings.
        ### let's make ivysettings.xml and add lockstrategy first. need to pass ivysettings field to pyspark
        export SPARK_JARS_CONFIGS='{"spark.jars.ivySettings":"$GITHUB_WORKSPACE/test/ivySettings.xml"}'
        export JAVA_HOME="${JAVA_HOME_11_X64:-$JAVA_HOME_11_arm64}"
        echo $SPARK_JARS_CONFIG
        python -m pytest -n auto test/test_* -v
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
