# File defining all the constants being used.


SCALA_LANGUAGE = "scala"
PYTHON_LANGUAGE = "python"

DATABRICKS_HOST = "DATABRICKS_HOST"
DATABRICKS_TOKEN = "DATABRICKS_TOKEN"

PROJECT_ID_PLACEHOLDER_KEY = "PROJECT_ID_PLACEHOLDER"
PROPHECY_URL_PLACEHOLDER_KEY = "PROPHECY_URL_PLACEHOLDER"
PROJECT_RELEASE_VERSION_PLACEHOLDER_KEY = "PROJECT_RELEASE_VERSION_PLACEHOLDER"

PROJECT_ID_PLACEHOLDER_REGEX = "__PROJECT_ID_PLACEHOLDER__"
PROPHECY_URL_PLACEHOLDER_REGEX = "__PROPHECY_URL_PLACEHOLDER__"
PROJECT_RELEASE_VERSION_PLACEHOLDER_REGEX = "__PROJECT_RELEASE_VERSION_PLACEHOLDER__"

PIPELINE_ID = "PipelineId"

PBT_FILE_NAME = "pbt_project.yml"
LANGUAGE = "language"
JOBS = "jobs"
PIPELINES = "pipelines"
PIPELINE_CONFIGURATIONS = "pipelineConfigurations"
BASE_PIPELINE = "basePipeline"
CONFIGURATIONS = "configurations"
JOBS = "jobs"

JSON_EXTENSION = ".json"

DBT_COMPONENT = "DBTComponent"
SCRIPT_COMPONENT = "ScriptComponent"
COMPONENTS_LITERAL = "components"

FABRIC_ID = "fabric_id"
SECRET_SCOPE = "secret_scope"
